# Generated by Django 2.1.7 on 2019-02-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20, verbose_name='班级名')),
                ('gdate', models.DateTimeField(verbose_name='成立时间')),
                ('ggirlnum', models.IntegerField(verbose_name='女生人数')),
                ('gboynum', models.IntegerField(verbose_name='男生人数')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否解散')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='姓名')),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField(verbose_name='年龄')),
                ('scontend', models.CharField(max_length=20, verbose_name='简介')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否存活')),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades')),
            ],
        ),
    ]
